cargo-features = ["edition2021"]

[package]
name = "jian_ai-webpages"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.18.0"
yew-router = "0.15.0"
wasm-bindgen = "0.2.74"
anyhow = "1.0.40"
serde_json = "1.0.64"
percent-encoding = "2.1.0"
